version: "3.9"

services:
  chat:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: locallhost-chat
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8888:8888"
    networks:
      - webnet

  nginx:
    image: nginx:stable-alpine
    container_name: locallhost-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl/certs:ro
      - ./static:/app/static:ro
    depends_on:
      - chat
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
