name: CI/CD  Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests (optional)
      run: |
        echo "Add any Python/Tornado tests here"

    - name: Build Docker image
      run: |
        docker build -t locallhost-chat:latest .

    - name: Push Docker image to Docker Hub
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: web4app/locallhost-chat:latest

    - name: Deploy to Server
      run: |
        ssh user@your-server "docker pull your-dockerhub-username/locallhost-chat:latest && \
        docker stop locallhost-chat || true && \
        docker rm locallhost-chat || true && \
        docker run -d --name locallhost-chat -p 8888:8888 
        your-dockerhub-username/locallhost-chat:latest"
        docker run -d --name locallhost-chat -p 50080:8888 
